package main;

import javax.swing.JFileChooser;
import main.simpleLogicGates.AND_Gate;

/**THIS CLASS HAS BEEN AUTO-GENERATED BY NETBEANS GUI EDITOR*/
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
	public JFileChooser fc;
    public MainFrame() {
        initComponents();
		fc = new JFileChooser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        mainPanel1 = new main.MainPanel();
        jTextField1 = new javax.swing.JTextField();
        mouseRealPos = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        mouseGridPos = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemOpen = new javax.swing.JMenuItem();
        menuItemSave = new javax.swing.JMenuItem();
        menuItemSaveAs = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        subMenuAddNew = new javax.swing.JMenu();
        subMenuSimpleLogic = new javax.swing.JMenu();
        menuOptionANDGate = new javax.swing.JMenuItem();
        menuOptionORGate = new javax.swing.JMenuItem();
        menuOptionNOTGate = new javax.swing.JMenuItem();
        menuOptionXORGate = new javax.swing.JMenuItem();
        subMenuAdvancedLogic = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TestFrame");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("mainFrame"); // NOI18N

        mainPanel1.setPreferredSize(new java.awt.Dimension(593, 600));

        javax.swing.GroupLayout mainPanel1Layout = new javax.swing.GroupLayout(mainPanel1);
        mainPanel1.setLayout(mainPanel1Layout);
        mainPanel1Layout.setHorizontalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        mainPanel1Layout.setVerticalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Mouse real position:");
        jTextField1.setOpaque(false);

        mouseRealPos.setText("jTextField2");

        jTextField3.setEditable(false);
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Mouse grid position:");
        jTextField3.setOpaque(false);

        mouseGridPos.setText("jTextField4");
        mouseGridPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mouseGridPosActionPerformed(evt);
            }
        });

        menuFile.setText("File");

        menuItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuItemOpen.setText("Open...");
        menuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFile(evt);
            }
        });
        menuFile.add(menuItemOpen);

        menuItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuItemSave.setText("Save...");
        menuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSaveFile(evt);
            }
        });
        menuFile.add(menuItemSave);

        menuItemSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemSaveAs.setText("Save As...");
        menuItemSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileAs(evt);
            }
        });
        menuFile.add(menuItemSaveAs);

        menuBar.add(menuFile);

        menuEdit.setText("Edit");
        menuBar.add(menuEdit);

        subMenuAddNew.setText("Add new...");

        subMenuSimpleLogic.setText("Simple Logic");

        menuOptionANDGate.setText("AND gate");
        menuOptionANDGate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOptionANDGateActionPerformed(evt);
            }
        });
        subMenuSimpleLogic.add(menuOptionANDGate);

        menuOptionORGate.setText("OR gate");
        subMenuSimpleLogic.add(menuOptionORGate);

        menuOptionNOTGate.setText("NOT gate");
        subMenuSimpleLogic.add(menuOptionNOTGate);

        menuOptionXORGate.setText("XOR gate");
        subMenuSimpleLogic.add(menuOptionXORGate);

        subMenuAddNew.add(subMenuSimpleLogic);

        subMenuAdvancedLogic.setText("Advanced Logic");
        subMenuAddNew.add(subMenuAdvancedLogic);

        menuBar.add(subMenuAddNew);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(mouseRealPos)
                    .addComponent(jTextField3)
                    .addComponent(mouseGridPos))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
            .addComponent(mainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mouseRealPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mouseGridPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void menuItemSaveFile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSaveFile
        if(fc.getSelectedFile() == null){
			this.saveFileAs(evt);
		} else {
			//TODO Saving
		}
    }//GEN-LAST:event_menuItemSaveFile
    private void openFile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFile
		int value = fc.showOpenDialog(Main.mainFrame);
		if(value == JFileChooser.APPROVE_OPTION){
			//TODO Open Dialog
		}
    }//GEN-LAST:event_openFile
    private void saveFileAs(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileAs
        int value = fc.showSaveDialog(Main.mainFrame);
		if(value == JFileChooser.APPROVE_OPTION){
			//TODO Saving
		}
    }//GEN-LAST:event_saveFileAs

    private void menuOptionANDGateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOptionANDGateActionPerformed
		mainPanel1.addLogicGate(new AND_Gate());
    }//GEN-LAST:event_menuOptionANDGateActionPerformed

    private void mouseGridPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mouseGridPosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mouseGridPosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    public main.MainPanel mainPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuItemOpen;
    private javax.swing.JMenuItem menuItemSave;
    private javax.swing.JMenuItem menuItemSaveAs;
    private javax.swing.JMenuItem menuOptionANDGate;
    private javax.swing.JMenuItem menuOptionNOTGate;
    private javax.swing.JMenuItem menuOptionORGate;
    private javax.swing.JMenuItem menuOptionXORGate;
    public javax.swing.JTextField mouseGridPos;
    public javax.swing.JTextField mouseRealPos;
    private javax.swing.JMenu subMenuAddNew;
    private javax.swing.JMenu subMenuAdvancedLogic;
    private javax.swing.JMenu subMenuSimpleLogic;
    // End of variables declaration//GEN-END:variables
}
